#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        FixedVoltagePowerSupply.py
#
#  Project :     Fixed Voltage Power Supply
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      srubio$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["FixedVoltagePowerSupply", "FixedVoltagePowerSupplyClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(FixedVoltagePowerSupply.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.additionnal_import

# Device States Description
# ON : 
# OFF : 


class FixedVoltagePowerSupply (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(FixedVoltagePowerSupply.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        FixedVoltagePowerSupply.init_device(self)
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_Voltage_read = 0.0
        self.attr_Current_read = 0.0
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.always_executed_hook

    # -------------------------------------------------------------------------
    #    FixedVoltagePowerSupply read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_Voltage(self, attr):
        self.debug_stream("In read_Voltage()")
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.Voltage_read) ENABLED START -----#
        attr.set_value(self.attr_Voltage_read)
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.Voltage_read
        
    def write_Voltage(self, attr):
        self.debug_stream("In write_Voltage()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.Voltage_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.Voltage_write
        
    def read_Current(self, attr):
        self.debug_stream("In read_Current()")
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.Current_read) ENABLED START -----#
        attr.set_value(self.attr_Current_read)
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.Current_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.read_attr_hardware


    # -------------------------------------------------------------------------
    #    FixedVoltagePowerSupply command methods
    # -------------------------------------------------------------------------
    
    def On(self):
        """ 
        """
        self.debug_stream("In On()")
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.On) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.On
        
    def Off(self):
        """ 
        """
        self.debug_stream("In Off()")
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.Off) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.Off
        

    #----- PROTECTED REGION ID(FixedVoltagePowerSupply.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.programmer_methods

class FixedVoltagePowerSupplyClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(FixedVoltagePowerSupply.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        'On':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'Off':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        'Voltage':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'Current':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(FixedVoltagePowerSupplyClass, FixedVoltagePowerSupply, 'FixedVoltagePowerSupply')
        #----- PROTECTED REGION ID(FixedVoltagePowerSupply.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	FixedVoltagePowerSupply.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
